### ISSUE TITLE
Erreur lors de la validation des fichiers Netex (non unicité des id sur AccessibilityAssessment)

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/tartare-tools#59]
Bonjour,

je teste le binaire `gtfs2netexfr`.

Globalement c'est top, merci pour le travail effectué !

J'ai cependant sur certain jeux de données une erreur quand je fais tourner sur les fichiers générés le [validateur de chouette](https://github.com/enroute-mobi/netex-cli-validator) (qui a l'air de simplement checker la conformité aux XSD)

```
678969:32: ERROR: Element '{http://www.netex.org.uk/netex}AccessibilityAssessment': Duplicate key-sequence ['FR:AccessibilityAssessment:0:', 'any'] in key identity-constraint '{http://www.netex.org.uk/netex}AccessibilityAssessment_AnyVersionedKey'.
```

Pas de chance j'ai cette erreur quand je valide le fichier `arrets.xml` du netex de [l'ile de france](https://transport.data.gouv.fr/datasets/horaires-prevus-sur-les-lignes-de-transport-en-commun-dile-de-france-gtfs/), et l'outil de validation met 1h à valider le fichier :sweat_smile: 

sinon pour aider dans ma recette je voulais savoir si vous avez un binaire qui fait netex2gtfs histoire que je regarde si on retombe sur quelque chose de pas trop éloigné quand on fait gtfs -> netex -> gtfs.
Si vous avez pas aucun soucis, c'est juste que je suis bien démuni pour savoir si le netex généré est correcte :laughing:

**Comment by woshilapin** [comment]
Alors, je vais commencer par répondre aux questions dont je connais déjà la réponse : non, nous n'avons pas de lecteur NeTEx France pour l'instant donc pas de `netexfr2gtfs` disponible.

Sinon, pour ton problème, on va essayer de regarder ça mais le planning est chargé. On va voir comment on priorise ça (ping @prhod).

**Comment by prhod** [comment]
@antoine-de merci pour le feed back :+1: 
Normalement nous aussi vérifions la conformité aux XSD, on n'a pas du tombé sur ce cas là ! 
On essaye de regarder ASAP, n'hésite pas  à remonter si le problème est urgent/bloquant de ton côté.

**Comment by ArnaudOggy** [comment]
@antoine-de 
On a la conformité Netex 1.9 (dans la CI) https://github.com/NeTEx-CEN/NeTEx
Pas forcément celle de Chouette.
https://github.com/CanalTP/transit_model/blob/master/src/documentation/ntfs_to_netex_france_specs.md#schema-validation

**Comment by antoine-de** [comment]
L'outil de chouette ne fait que faire tourner les xsd de netex, je pense que c'est juste un cas limite qui a du passer vos filtres @ArnaudOggy (`xmllint` me donne la meme erreur)

@prhod non vraiment rien d'urgent de notre coté, je faisais juste une recette de la conversion, donc je voulais juste tracer le problème.

Merci de votre réactivité !

**Comment by ArnaudOggy** [comment]
Ah ok. Donc petite coquille chez nous alors. 
Il faudrait analyser la data en amont produisant le cas de figure rencontré.

**Comment by ArnaudOggy** [comment]
Hello @antoine-de, 
Le fix sera dispo avec la prochaine version de Transit_Model (> 0.15.2)
https://crates.io/crates/transit_model
Pour info j'ai fait tourner l'intégralité du validateur Netex (1.09) sur tout le jeu de données Netex-France généré. C'est ok.

**Comment by antoine-de** [comment]
:heart: 

merci !

(pour être sur de comprendre, t'as fait tourner la validation des xsd sur le jeu de données généré de l'ile de france ?)

**Comment by ArnaudOggy** [comment]
Sur le Netex profil France généré à partir du GTFS de l'ile de france oui.
https://transport.data.gouv.fr/datasets/horaires-prevus-sur-les-lignes-de-transport-en-commun-dile-de-france-gtfs/
2.2 Go de data en sortie, 4h de validation (comme toi).
Tous les flux (racines ou dossiers offre) sont valides.

**Comment by ArnaudOggy** [comment]
@antoine-de 
Le fix est à ta dispo (après pull/build) :wink:
